DROP TABLE IF EXISTS "APPORT_MANA";
CREATE TABLE APPORT_MANA
   (
   ID_CARTE SMALLINT NOT NULL ,
   APPORT_ROUGE SMALLINT  ,
   APPORT_BLANC SMALLINT  ,
   APPORT_NOIR SMALLINT  ,
   APPORT_BLEU SMALLINT  ,
   APPORT_VERT SMALLINT  ,
   ID_MANA SMALLINT NOT NULL 
,
     PRIMARY KEY (ID_MANA) CONSTRAINT PK_APPORT_MANA
   );
INSERT INTO "APPORT_MANA" VALUES(4,NULL,1,NULL,NULL,NULL,1);
DROP TABLE IF EXISTS "CARTE";
CREATE TABLE CARTE
   (
   ID_CARTE SMALLINT NOT NULL ,
   NOM_CARTE CHAR(32)  ,
   TYPE SMALLINT  ,
   URL_IMAGE VARCHAR(128)  ,
   COULEUR_CARTE VARCHAR(128)  ,
   ATTACK SMALLINT  ,
   DEFENSE SMALLINT  ,
   FONCTION_LIEE CHAR(32)  
,
     PRIMARY KEY (ID_CARTE) CONSTRAINT PK_CARTE
   );
INSERT INTO "CARTE" VALUES(3,'voyage vers le néant',3,'./cartes_magic/005','blanc',NULL,NULL,'A');
INSERT INTO "CARTE" VALUES(2,'chasseciel leonin',2,'./cartes_magic/004','blanc',2,2,NULL);
INSERT INTO "CARTE" VALUES(1,'pecheur celeste jor',2,'./cartes_magic/003','blanc',2,3,NULL);
INSERT INTO "CARTE" VALUES(4,'plaine',1,'./cartes_magic/014','blanc',NULL,NULL,NULL);
DROP TABLE IF EXISTS "COUT_INVOQUE";
CREATE TABLE COUT_INVOQUE
   (
   ID_CARTE SMALLINT NOT NULL ,
   COUT_ROUGE SMALLINT  ,
   COUT_BLANC SMALLINT  ,
   COUT_NOIR SMALLINT  ,
   COUT_BLEU SMALLINT  ,
   COUT_VERT SMALLINT  ,
   COUT_MULTI SMALLINT  ,
   ID_COUT SMALLINT NOT NULL 
,
     PRIMARY KEY (ID_COUT) CONSTRAINT PK_COUT_INVOQUE
   );
INSERT INTO "COUT_INVOQUE" VALUES(1,NULL,1,NULL,NULL,NULL,1,1);
INSERT INTO "COUT_INVOQUE" VALUES(2,NULL,2,NULL,NULL,NULL,NULL,2);
INSERT INTO "COUT_INVOQUE" VALUES(3,NULL,1,NULL,NULL,NULL,1,3);
DROP TABLE IF EXISTS "DECK";
CREATE TABLE DECK
   (
   ID_DECK SMALLINT NOT NULL ,
   NAME VARCHAR(128)  
,
     PRIMARY KEY (ID_DECK) CONSTRAINT PK_DECK
   );
DROP TABLE IF EXISTS "PERSO";
CREATE TABLE PERSO
   (
   ID_PERSO SMALLINT NOT NULL ,
   PSEUDO VARCHAR(128)  ,
   XP INTEGER  
,
     PRIMARY KEY (ID_PERSO) CONSTRAINT PK_PERSO
   );
