DROP TABLE IF EXISTS "APPORT_MANA";
CREATE TABLE APPORT_MANA
   (
   ID_CARTE SMALLINT NOT NULL ,
   APPORT_ROUGE SMALLINT  ,
   APPORT_BLANC SMALLINT  ,
   APPORT_NOIR SMALLINT  ,
   APPORT_BLEU SMALLINT  ,
   APPORT_VERT SMALLINT  ,
   ID_MANA SMALLINT NOT NULL 
,
     PRIMARY KEY (ID_MANA) CONSTRAINT PK_APPORT_MANA
   );
DROP TABLE IF EXISTS "CARTE";
CREATE TABLE CARTE
   (
   ID_CARTE SMALLINT NOT NULL ,
   NOM_CARTE CHAR(32)  ,
   TYPE SMALLINT  ,
   URL_IMAGE VARCHAR(128)  ,
   COULEUR_CARTE VARCHAR(128)  ,
   ATTACK SMALLINT  ,
   DEFENSE SMALLINT  ,
   FONCTION_LIEE CHAR(32)  
,
     PRIMARY KEY (ID_CARTE) CONSTRAINT PK_CARTE
   );
DROP TABLE IF EXISTS "COUT_INVOQUE";
CREATE TABLE COUT_INVOQUE
   (
   ID_CARTE SMALLINT NOT NULL ,
   COUT_ROUGE SMALLINT  ,
   COUT_BLANC SMALLINT  ,
   COUT_NOIR SMALLINT  ,
   COUT_BLEU SMALLINT  ,
   COUT_VERT SMALLINT  ,
   COUT_MULTI SMALLINT  ,
   ID_COUT SMALLINT NOT NULL 
,
     PRIMARY KEY (ID_COUT) CONSTRAINT PK_COUT_INVOQUE
   );
DROP TABLE IF EXISTS "DECK";
CREATE TABLE DECK
   (
   ID_DECK SMALLINT NOT NULL ,
   NAME VARCHAR(128)  
,
     PRIMARY KEY (ID_DECK) CONSTRAINT PK_DECK
   );
DROP TABLE IF EXISTS "PERSO";
CREATE TABLE PERSO
   (
   ID_PERSO SMALLINT NOT NULL ,
   PSEUDO VARCHAR(128)  ,
   XP INTEGER  
,
     PRIMARY KEY (ID_PERSO) CONSTRAINT PK_PERSO
   );
