	cur.execute ( ''' CREATE TABLE  APPARTIEN  (
   ID_PERSO  smallint(2) NOT NULL,
   ID_DECK  smallint(2) NOT NULL,
  PRIMARY KEY ( ID_PERSO , ID_DECK ),
  KEY  I_FK_APPARTIEN_PERSO  ( ID_PERSO ),
  KEY  I_FK_APPARTIEN_DECK  ( ID_DECK ),
  CONSTRAINT  appartien_ibfk_2  FOREIGN KEY ( ID_DECK ) REFERENCES  DECK  ( ID_DECK ),
  CONSTRAINT  appartien_ibfk_1  FOREIGN KEY ( ID_PERSO ) REFERENCES  PERSO  ( ID_PERSO )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ''' )
	cur.execute ( '''CREATE TABLE  APPORT_MANA  (
   ID_MANA  smallint(2) NOT NULL AUTO_INCREMENT,
   ID_CARTE  smallint(2) NOT NULL,
   APPORT_ROUGE  smallint(1) DEFAULT NULL,
   APPORT_BLANC  smallint(1) DEFAULT NULL,
   APPORT_NOIR  smallint(1) DEFAULT NULL,
   APPORT_BLEU  smallint(1) DEFAULT NULL,
   APPORT_VERT  smallint(1) DEFAULT NULL,
  PRIMARY KEY ( ID_MANA ),
  KEY  I_FK_APPORT_MANA_CARTE  ( ID_CARTE ),
  CONSTRAINT  apport_mana_ibfk_1  FOREIGN KEY ( ID_CARTE ) REFERENCES  CARTE  ( ID_CARTE )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 
 ''' )
	cur.execute ( '''CREATE TABLE  CARTE  (
   ID_CARTE  smallint(2) NOT NULL AUTO_INCREMENT,
   NOM_CARTE  char(32) DEFAULT NULL,
   TYPE_CARTE  smallint(1) DEFAULT NULL COMMENT '1:terrain,2:creature,3:enchantement,4:rituel,5:ephemere',
   URL_IMAGE  varchar(128) DEFAULT NULL,
   COULEUR_CARTE  varchar(128) DEFAULT NULL,
   ATTACK  smallint(2) DEFAULT NULL,
   DEFENSE  smallint(2) DEFAULT NULL,
   FONCTION_LIEE  char(32) DEFAULT NULL,
  PRIMARY KEY ( ID_CARTE )
) ENGINE=InnoDB DEFAULT CHARSET=utf8  ''' )
	cur.execute ( '''CREATE TABLE  COUT_INVOQUE  (
   ID_COUT  smallint(2) NOT NULL AUTO_INCREMENT,
   ID_CARTE  smallint(2) NOT NULL,
   COUT_ROUGE  smallint(1) DEFAULT NULL,
   COUT_BLANC  smallint(1) DEFAULT NULL,
   COUT_NOIR  smallint(1) DEFAULT NULL,
   COUT_BLEU  smallint(1) DEFAULT NULL,
   COUT_VERT  smallint(1) DEFAULT NULL,
   COUT_MULTI  smallint(1) DEFAULT NULL,
  PRIMARY KEY ( ID_COUT ),
  KEY  I_FK_COUT_INVOQUE_CARTE  ( ID_CARTE ),
  CONSTRAINT  cout_invoque_ibfk_1  FOREIGN KEY ( ID_CARTE ) REFERENCES  CARTE  ( ID_CARTE )
) ENGINE=InnoDB DEFAULT CHARSET=utf8  ''' )
	cur.execute ( '''CREATE TABLE  DECK  (
   ID_DECK  smallint(2) NOT NULL AUTO_INCREMENT,
   NAME  varchar(128) DEFAULT NULL,
  PRIMARY KEY ( ID_DECK )
) ENGINE=InnoDB DEFAULT CHARSET=utf8  ''' )
	cur.execute ( ''' CREATE TABLE  LIE  (
   ID_DECK  smallint(2) NOT NULL,
   ID_CARTE  smallint(2) NOT NULL,
   QUANTITE_CARTE  smallint(2) DEFAULT NULL,
  PRIMARY KEY ( ID_DECK , ID_CARTE ),
  KEY  I_FK_LIE_DECK  ( ID_DECK ),
  KEY  I_FK_LIE_CARTE  ( ID_CARTE ),
  CONSTRAINT  lie_ibfk_2  FOREIGN KEY ( ID_CARTE ) REFERENCES  CARTE  ( ID_CARTE ),
  CONSTRAINT  lie_ibfk_1  FOREIGN KEY ( ID_DECK ) REFERENCES  DECK  ( ID_DECK )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ''' )
	cur.execute ( ''' CREATE TABLE  PERSO  (
   ID_PERSO  smallint(2) NOT NULL AUTO_INCREMENT,
   PSEUDO  varchar(128) DEFAULT NULL,
   XP  bigint(4) DEFAULT NULL,
  PRIMARY KEY ( ID_PERSO )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ''' )	
