CREATE TABLE COUT_INVOQUE
   (
   ID_COUT SMALLINT NOT NULL ,
   ID_CARTE SMALLINT NOT NULL ,
   COUT_ROUGE SMALLINT  ,
   COUT_BLANC SMALLINT  ,
   COUT_NOIR SMALLINT  ,
   COUT_BLEU SMALLINT  ,
   COUT_VERT SMALLINT  ,
   COUT_MULTI SMALLINT  
,
     PRIMARY KEY (ID_COUT) CONSTRAINT PK_COUT_INVOQUE
   );



CREATE  INDEX I_FK_COUT_INVOQUE_CARTE
     ON COUT_INVOQUE (ID_CARTE ASC);

CREATE TABLE CARTE
   (
   ID_CARTE SMALLINT NOT NULL ,
   NOM_CARTE CHAR(32)  ,
   TYPE_CARTE SMALLINT  ,
   URL_IMAGE VARCHAR(128)  ,
   COULEUR_CARTE VARCHAR(128)  ,
   ATTACK SMALLINT  ,
   DEFENSE SMALLINT  ,
   FONCTION_LIEE CHAR(32)  ,
   CIBLE SMALLINT  ,
   CREATURE SMALLINT  ,
   JOUEUR SMALLINT  
,
     PRIMARY KEY (ID_CARTE) CONSTRAINT PK_CARTE
   );


CREATE TABLE APPORT_MANA
   (
   ID_MANA SMALLINT NOT NULL ,
   ID_CARTE SMALLINT NOT NULL ,
   APPORT_ROUGE SMALLINT  ,
   APPORT_BLANC SMALLINT  ,
   APPORT_NOIR SMALLINT  ,
   APPORT_BLEU SMALLINT  ,
   APPORT_VERT SMALLINT  
,
     PRIMARY KEY (ID_MANA) CONSTRAINT PK_APPORT_MANA
   );



CREATE  INDEX I_FK_APPORT_MANA_CARTE
     ON APPORT_MANA (ID_CARTE ASC);



CREATE TABLE PERSO
   (
   ID_PERSO SMALLINT NOT NULL ,
   PSEUDO VARCHAR(128)  ,
   XP INTEGER  
,
     PRIMARY KEY (ID_PERSO) CONSTRAINT PK_PERSO
   );



CREATE TABLE DECK
   (
   ID_DECK SMALLINT NOT NULL ,
   NAME VARCHAR(128)  
,
     PRIMARY KEY (ID_DECK) CONSTRAINT PK_DECK
   );



CREATE TABLE LIE
   (
   ID_DECK SMALLINT NOT NULL ,
   ID_CARTE SMALLINT NOT NULL ,
   QUANTITE_CARTE SMALLINT  
,
     PRIMARY KEY (ID_DECK, ID_CARTE) CONSTRAINT PK_LIE
   );



CREATE  INDEX I_FK_LIE_DECK
     ON LIE (ID_DECK ASC);

CREATE  INDEX I_FK_LIE_CARTE
     ON LIE (ID_CARTE ASC);



CREATE TABLE APPARTIEN
   (
   ID_PERSO SMALLINT NOT NULL ,
   ID_DECK SMALLINT NOT NULL 
,
     PRIMARY KEY (ID_PERSO, ID_DECK) CONSTRAINT PK_APPARTIEN
   );



CREATE  INDEX I_FK_APPARTIEN_PERSO
     ON APPARTIEN (ID_PERSO ASC);

CREATE  INDEX I_FK_APPARTIEN_DECK
     ON APPARTIEN (ID_DECK ASC);



ALTER TABLE COUT_INVOQUE ADD (FOREIGN KEY (ID_CARTE)
      REFERENCES CARTE (ID_CARTE)
      CONSTRAINT FK_COUT_INVOQUE_CARTE );

ALTER TABLE APPORT_MANA ADD (FOREIGN KEY (ID_CARTE)
      REFERENCES CARTE (ID_CARTE)
      CONSTRAINT FK_APPORT_MANA_CARTE );

ALTER TABLE LIE ADD (FOREIGN KEY (ID_DECK)
      REFERENCES DECK (ID_DECK)
      CONSTRAINT FK_LIE_DECK );

ALTER TABLE LIE ADD (FOREIGN KEY (ID_CARTE)
      REFERENCES CARTE (ID_CARTE)
      CONSTRAINT FK_LIE_CARTE );

ALTER TABLE APPARTIEN ADD (FOREIGN KEY (ID_PERSO)
      REFERENCES PERSO (ID_PERSO)
      CONSTRAINT FK_APPARTIEN_PERSO );

ALTER TABLE APPARTIEN ADD (FOREIGN KEY (ID_DECK)
      REFERENCES DECK (ID_DECK)
      CONSTRAINT FK_APPARTIEN_DECK );



